name: hiegz

services:
  tunnel:
    image: cloudflare/cloudflared:2026.3.0
    restart: unless-stopped
    command: tunnel --no-autoupdate run

    env_file:
      - ./env/cloudflared.env

    networks:
      - network

  vaultwarden:
    image: vaultwarden/server:1.35.8-alpine
    restart: unless-stopped

    env_file:
      - "env/vaultwarden.env"

    volumes:
      - ./volumes/vw_data:/data/

    networks:
      - network

networks:
  network:
    driver: bridge
